repos:
  - repo: local
    hooks:
      - id: hardcoded-rules-check
        name: Hardcoded rules check
        entry: scripts/precommit_hardcoded_rules.sh
        language: system
        stages: [commit]
