version: "3.9"

name: vector-wave

networks:
  vector-wave:
    driver: bridge

volumes:
  chroma_data:
  topic_manager_data:

services:
  chromadb:
    image: chromadb/chroma:0.5.3
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8000/api/v2/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks: [vector-wave]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks: [vector-wave]

  editorial-service:
    build: ./editorial-service
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
      - REDIS_URL=redis://redis:6379
      - SERVICE_PORT=8040
    depends_on:
      chromadb:
        condition: service_started
    ports:
      - "8040:8040"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8040/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks: [vector-wave]

  crewai-orchestrator:
    build: ./crewai-orchestrator
    environment:
      - EDITORIAL_SERVICE_URL=http://editorial-service:8040
      - HARVESTER_URL=http://harvester:8043
      - TRIAGE_POLICY_PATH=/app/config/triage_policy.yaml
      - TRIAGE_POLICY_SCHEMA_PATH=/app/config/triage_policy.schema.json
      - REDIS_URL=redis://redis:6379
    depends_on:
      editorial-service:
        condition: service_started
    ports:
      - "8042:8042"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8042/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks: [vector-wave]

  topic-manager:
    build: ./topic-manager
    environment:
      - SERVICE_PORT=8041
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
      - EMBEDDINGS_PROVIDER=${EMBEDDINGS_PROVIDER:-openai}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_EMBEDDING_MODEL=${OPENAI_EMBEDDING_MODEL:-text-embedding-3-small}
      - TOPIC_MANAGER_DB=/data/topics.db
      - INDEX_REINDEX_CRON=*/10 * * * *
    ports:
      - "8041:8041"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8041/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks: [vector-wave]
    volumes:
      - topic_manager_data:/data

  publishing-orchestrator:
    profiles: ["publishing"]
    build: ./kolegium/publishing-orchestrator
    depends_on:
      editorial-service:
        condition: service_started
    networks: [vector-wave]

  linkedin-ppt:
    profiles: ["publishing"]
    build: ./kolegium/linkedin_ppt_generator
    networks: [vector-wave]

  analytics-service:
    profiles: ["analytics"]
    build: ./kolegium/analytics-service
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      - CHROMADB_URL=http://chromadb:8000
      - SERVICE_PORT=8081
    depends_on:
      chromadb:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks: [vector-wave]

  gamma-ppt-generator:
    profiles: ["gamma"]
    build: ./kolegium/gamma-ppt-generator
    environment:
      - GAMMA_API_KEY=${GAMMA_API_KEY:-}
      - HOST=0.0.0.0
      - SERVICE_PORT=8003
      - DEBUG=false
    ports:
      - "8003:8003"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks: [vector-wave]

  harvester:
    profiles: ["harvester"]
    build:
      context: ./harvester
      dockerfile: Dockerfile
    container_name: trend-harvester
    env_file:
      - .env
    ports:
      - "8043:8043"
    volumes:
      - ./harvester/src:/home/appuser/app/src
    environment:
      - EDITORIAL_SERVICE_URL=http://editorial-service:8040
      - TOPIC_MANAGER_URL=http://topic-manager:8041
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
      - HARVEST_FETCH_LIMIT=${HARVEST_FETCH_LIMIT:-50}
      - SELECTIVE_PROFILE_THRESHOLD=${SELECTIVE_PROFILE_THRESHOLD:-0.7}
      - SELECTIVE_NOVELTY_THRESHOLD=${SELECTIVE_NOVELTY_THRESHOLD:-0.8}
    depends_on:
      - chromadb
      - editorial-service
      - topic-manager
    networks:
      - vector-wave
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8043/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

