services:
  editorial-service:
    build: .
    ports:
      - "8040:8040"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8040/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s