name: Hardcoded Rules Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # Do not auto-init all submodules here — some are private/not available to GITHUB_TOKEN
        # We'll init only the required submodule(s) explicitly in the next step
      - name: Configure HTTPS for GitHub submodules
        run: |
          git config --global url.https://github.com/.insteadOf git@github.com:
          git config --global url.https://github.com/.insteadOf ssh://git@github.com/
          # Force kolegium submodule to use HTTPS explicitly
          git config submodule.kolegium.url https://github.com/hretheum/vector-wave-editorial-crew.git
      - name: Init required submodule (kolegium only)
        run: |
          git submodule update --init --depth 1 kolegium
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install ripgrep
        run: sudo apt-get update && sudo apt-get install -y ripgrep
      - name: Run hardcoded rules detection
        run: |
          python scripts/discover_hardcoded_rules.py || true
          rg -n 'forbidden_phrases|required_elements|style_patterns|default_rules|banned_words|weasel_words' kolegium/ -g '!**/{tests,mocks,backup,historical}/**' | tee /tmp/hits.txt || true
          if [ -s /tmp/hits.txt ]; then
            echo "Hardcoded rules detected:" >&2
            cat /tmp/hits.txt >&2
            exit 1
          fi
