name: Sync CrewAI Documentation

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Update CrewAI docs submodule to latest main
        run: |
          git submodule update --init --remote knowledge-base/knowledge-base/data/crewai-docs

          # Detect changes in parent repo for the submodule path
          if git diff --quiet --exit-code -- knowledge-base/knowledge-base/data/crewai-docs; then
            echo "Documentation is up to date"
            exit 0
          fi

          echo "Documentation updated; committing in parent repo..."
          git add knowledge-base/knowledge-base/data/crewai-docs
          git commit -m "chore: Update CrewAI documentation [auto-sync]"
          git push origin main